version: 2.1 

 

jobs: 

  build-and-test:  

    machine: 
      docker_layer_caching: true 
      image: ubuntu-2204:2024.01.2 

        

    steps: 

      - checkout 
      
      - run: make docker_push 
      - run: make deps 
      - run: make docker_build 
      - run: make test       

workflows: 

  basic:  

    jobs: 

      - build-and-test 
      